name: Validate JSON
on: [push, pull_request]
jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate jsons
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./arena.schema
          json_path_pattern: .*.json$
          send_comment: true
